### PR TITLE
g4: update partition size

### PR DESCRIPTION
**Pull request by eleboucher**

### CODE REVIEW

**Comment by C457** [comment]
The partition sizes are device specific. https://github.com/TeamRegular/android_device_lge_h811/blob/cm-12.1/BoardConfig.mk#L28 my trees are also based off h811 10N and g4stylus I don't know how much of a difference that makes for h815 10C though. Also is there a reason why you removed flag for ril class? Does it cause issues on g4?

**Comment by eleboucher** [comment]
I use it for both phone (the build break with your tree cause of that)  we get a fully working ril with the ril class

**Comment by eleboucher** [comment]
My bad you fixed the block size (but all the partition size are better in the common tree)

**Comment by C457** [comment]
If the partition sizes aren't the same I don't think they should be in common. Partition sizes are never included in common as they are device specific especially with cdma devices they are typically smaller.

**Pull request closed without merging**
